default:
  - _self_

batch_size: 256
dataset: TIN
device: cuda:8
bias: True
layer_type: BPConv
decorrelation_method: None
decor_lr: 1e-4
n_hidden_layers: 4
hidden_layer_size: 64
loss_func_type: CCE
optimizer_type: Adam
fwd_lr: 1e-6
seed: 42
nb_epochs: 10
loud: True

wandb:
  project: "CorrelationsRuinGD"
  mode: "offline"
  entity: "nasiryahm"