default:
  - _self_

batch_size: 256 #Default fixed batch size
dataset: CIFAR10 #Options: CIFAR10, CIFAR100, TIN (TinyImageNet)
device: cuda:4
bias: True
layer_type: FAConv #Options: BP, NP, FA, FAConv, BPConv
regularizer_strength: 0.0 
decor_lr: 1e-5 #Decorrelation learning rate
fwd_lr: 1e-4  #Forward learning rate
loss_func_type: CCE #Options: CCE, MSE
optimizer_type: Adam #Options: Adam, SGD - this is only for the regular network weights
seed: 42
nb_epochs: 100 #Number of epochs
loud: True
validation: False #If True, the model will be validated on the validation set

wandb:
  project: "CorrelationsRuinGD"
  mode: "offline"
  entity: "nasiryahm"