default:
  - _self_

batch_size: 256
dataset: CIFAR10
device: cuda:6
bias: True
layer_type: BP
decorrelation_method: 'copi'
regularizer_strength: 0.0 #1e-3 #0.1 (1 is 0.1, 2 is 1e-3, 4 is 1e-6)
decor_lr: 0.000015625 # Values for run w/ reg test for FA TIN
fwd_lr: 0.00015625
n_hidden_layers: 4
hidden_layer_size: 1000
loss_func_type: CCE
optimizer_type: Adam
seed: 42
nb_epochs: 100
loud: True
validation: True

wandb:
  project: "CorrelationsRuinGD"
  mode: "offline"
  entity: "nasiryahm"